### ISSUE TITLE
[Модель] "Стол"

### ISSUE THREAD

**Issue by SijyKijy** [vidinalex/Plant-Market#34]
- [x] Голая модель;
- [x] UV "Столешница";
- [x] UV "Ножка1";
- [x] UV "Ножка2";
- [x] UV "Ножка3";
- [x] UV "Ножка4";
- [ ] Текстура.

Cтол для #21 и #22

**Comment by JIJITANKO** [comment]
Стол готов для наложения текстурки, хотя конечно полигончиков многовато 👍🏿 :

- https://drive.google.com/drive/folders/1heMZuTUkme_SsJXUttA4be6W_yqQQ0xV
